spring:
  application:
    name: kariya-interview-mock

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.152.55:3308/db_kariya_admin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: ENC(zl2CNxlJlwDlMzsOXDsCusB8jKOLvDeMJqqonbDwP9Ez8kTtHxdqx5noJWfVf5r7)
      password: ENC(qHmjHV4A41HYzWpW9VvsKhccl+awK5H/EJOVLbqULtJlrv1Fv4777RoOnfddyHK6)

      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20


  data:
    redis:
      host: 124.222.152.55
      port: 6381
      database: 0
      password: ENC(qBbHmK1FX4rBdxr1dPqyb/GcB7vrSwtORvRbvIJaXNfrzmtHuoyHSo+bDHxpCZdp)
      timeout: 3000ms
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000ms

server:
  port: 9999


jwt:
  secret: ${JWT_SECRET:kariya-interview-mock-admin-jwt-secret} # replace-with-your-local-jwt-secret
  access-token-expire-minutes: 15

auth:
  access-token-expire-minutes: 15
  refresh-token-expire-hours: 8
  remember-me-ref resh-token-expire-days: 14
  refresh-token-cookie-name: refresh_token
  device-id-cookie-name: device_id
  refresh-token-cookie-path: /
  cookie-secure: false
  cookie-same-site: Lax
  refresh-reuse-grace-seconds: 5

mybatis-plus:
  global-config:
    banner: false
